# Configurations
title:            RoboHearts DEV
longtitle:        RoboHearts DEV
author:           Emile Kroeger
email:            contact@robohearts.eu
description: >
  Some documentation for NAO.

version:          1.0
gitbook_version:  3.2.3

url:              'https://roboheartsdev.github.io'
baseurl:          '/landing'
rss:              RSS

# bootstrap: use the local theme files

toc:
  enabled: true
  h_min: 1
  h_max: 3

# customize the link favicon in header, will be {{site.baseurl}}/{{site.favicon_path}}
favicon_path:     /assets/favicon.ico

# markdown render engine.
markdown:         kramdown
kramdown:
  auto_ids:               true
  input:                  GFM
  math_engine:            mathjax
  smart_quotes:           lsquo,rsquo,ldquo,rdquo
  toc_levels:             1..6
  syntax_highlighter:     rouge
  syntax_highlighter_opts:
    guess_lang:           true

syntax_highlighter_style: colorful

markdown_ext:             markdown,mkdown,mkdn,mkd,md

# Permalinks
permalink:                /:categories/:year-:month-:day-:title:output_ext

# Disqus comments
# disqushandler:            roboheartsdev

twitter_username: EmileAndHisBots
github_username: RoboHeartsDEV


exclude:
  - _drafts

# Include assets in build
include:
  - assets

collections:
  pages:
    output: true
    permalink: /:collection/:path/

page_width: 800px

destination:      ./_site
incremental:      false
regenerate:       true

plugins:
  - jekyll-feed
  - jekyll-readme-index
  - jemoji
